# To use these install Rest Client in vs code



GET http://localhost:3000/


### getting list of questions
GET http://localhost:3000/api/questions 



### creating a question

POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "description": "this is test3 description of question",
    "options": ["test3 option 1","test3 option 2","test3 option 3","test3 option 4"],
    "correct_answer": "test3 correct answer",
    "explanation":"test3 explanation",
    "topic":"test3 topic",
    "posted_by": "test3 user",
    "likes": 1,
    "dislikes": 0
}


### Get a question by id

GET http://localhost:3000/api/questions/id
#e.g. id:60f0382ad91de80668e76d52


### Update a question by id

PATCH http://localhost:3000/api/questions/60f0382ad91de80668e76d52
Content-Type: application/json

{
    "description":"test the description of question"
}

### Delete a question by id

DELETE  http://localhost:3000/api/questions/60f055fab5cda6423c959dfe


### test
GET  http://localhost:3000/test/1415424
### test
POST  http://localhost:3000/test
Content-Type: application/json

{
    "name":"878",
    "description":"yeryerher"
}