# To use these install Rest Client in vs code

### getting list of questions
GET http://localhost:3000/questions 



### creating a question
POST http://localhost:3000/questions


### Get a question by id
GET http://localhost:3000/questions/id


### Update a question by id
PATCH http://localhost:3000/questions/id

### Delete a question by id
DELETE  http://localhost:3000/questions/id